.TH HUAYRA-TDA-PLAYER 1 "May 16, 2014"
.SH NAME
huayra-tda-player \- Reproductor de Televisión Digital para Linux
.SH SYNOPSIS
.B huayra-tda-player
.SH DESCRIPTION
.B HUAYRA-TDA-PLAYER
es un reproductor de Televisión Digital para Linux.
Escrito en Python + Qt4 y utiliza vlc para reproducir video y audio.

.SH SEE ALSO
Codigo Online: https://github.com/HuayraLinux/huayra-tda
.PP
.SH AUTHOR
Este manual ha sido escrito por Mauro <mauro@krutt.org>, para Huayra
GNU/Linux (pero puede ser utilizado por otros).
